/* 
	Editor: http://www.visualmicro.com
	        visual micro and the arduino ide ignore this code during compilation. this code is automatically maintained by visualmicro, manual changes to this file will be overwritten
	        the contents of the Visual Micro sketch sub folder can be deleted prior to publishing a project
	        all non-arduino files created by visual micro and all visual studio project or solution files can be freely deleted and are not required to compile a sketch (do not delete your own code!).
	        note: debugger breakpoints are stored in '.sln' or '.asln' files, knowledge of last uploaded breakpoints is stored in the upload.vmps.xml file. Both files are required to continue a previous debug session without needing to compile and upload again
	
	Hardware: Arduino Mega w/ ATmega2560 (Mega 2560), Platform=avr, Package=arduino
*/

#define __AVR_ATmega2560__
#define ARDUINO 101
#define ARDUINO_MAIN
#define F_CPU 16000000L
#define __AVR__
#define __cplusplus
extern "C" void __cxa_pure_virtual() {;}


#include "C:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\mega\pins_arduino.h" 
#include "C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\arduino.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\Robo3dR1V2.ino"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\BlinkM.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\BlinkM.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\Configuration.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\ConfigurationStore.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\ConfigurationStore.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\Configuration_adv.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\DOGMbitmaps.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT800.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT800Impl.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_FilamentScreen.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_HomeScreen.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_Images.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_PreheatScreen.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_Print_HeatingScreen.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_PrintingScreen.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_ScreenBase.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_ScreenBase.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_ScreensManager.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_SdCardScreen.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_SettingsScreen.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_SplashScreen.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_StartupScreen.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_Strings.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT843_UtilitiesScreen.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT_Breakout_4DLCD_FT843.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT_GC.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\FT_Transport_SPI.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\LiquidCrystalRus.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\LiquidCrystalRus.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\Marlin.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\Marlin.ino"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\MarlinSerial.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\MarlinSerial.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\Marlin_main.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\ROBO_Configuration.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\Sd2Card.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\Sd2Card.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\Sd2PinMap.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\SdBaseFile.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\SdBaseFile.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\SdFatConfig.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\SdFatStructs.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\SdFatUtil.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\SdFatUtil.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\SdFile.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\SdFile.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\SdInfo.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\SdVolume.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\SdVolume.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\Servo.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\Servo.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_CC3000.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_CC3000.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_CC3000_Callbacks.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_CC3000_Callbacks.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_CC3000_Client.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_CC3000_Client.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_CC3000_SPI.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_CC3000_SPI.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_Manager.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_Manager.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_cc3000_common.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_cc3000_common.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_common.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_evnt_handler.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_evnt_handler.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_hci.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_hci.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_host_driver_version.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_netapp.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_netapp.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_nvmem.c"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_nvmem.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_security.c"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_security.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_socket.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_socket.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_wlan.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\WIFI_wlan.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\cardreader.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\cardreader.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\digipot_mcp4451.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\dogm_font_data_marlin.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\dogm_lcd_implementation.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\fastio.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\language.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\motion_control.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\motion_control.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\pins.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\planner.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\planner.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\qr_solve.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\qr_solve.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\speed_lookuptable.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\stepper.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\stepper.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\temperature.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\temperature.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\thermistortables.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\ultralcd.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\ultralcd.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\ultralcd_implementation_hitachi_HD44780.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\ultralcd_st7920_u8glib_rrd.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\vector_3.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\vector_3.h"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\watchdog.cpp"
#include "C:\Users\sherif\Documents\Arduino\Robo3dR1V2\watchdog.h"
